runner:
  capacity: 1
  labels:
    - open-grind-orchestrator:docker://git.opengrind.org/open-grind/open-grind-orchestrator@sha256:ad5c6413984786928aa80206c267a5c0c61aa5c02e4126dc913912fb08ddf918
container:
  privileged: false
  valid_volumes: []
  docker_host: "-"
  network: ""
server:
  connections:
    open-grind-orchestrator:
      url: https://git.opengrind.org/
      uuid: b8f3742b-bff3-4c93-bbcb-6a5fcc8a97e9
      token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa